---
- name: Configure kernel and GRUB settings
  hosts: all
  become: true
  tasks:
    - name: Get list of installed 5.15.0 kernel packages
      shell: dpkg -l | grep "^ii" | grep -E "linux-(image|headers|modules|modules-extra)-5\.15\.0-[0-9]+" | awk '{print $2}'
      register: kernel_packages
      changed_when: false

    - name: Hold kernel 5.15.0 packages
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop: "{{ kernel_packages.stdout_lines }}"
      when: kernel_packages.stdout_lines | length > 0

    - name: Modify GRUB configuration
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_DEFAULT='
        line: 'GRUB_DEFAULT="Advanced options for Ubuntu>Ubuntu, with Linux 5.15.0-94-generic"'
        backup: yes

    - name: Update GRUB
      command: update-grub
      register: grub_update
      changed_when: grub_update.rc == 0

    - name: Reboot system
      reboot:
        msg: "Rebooting to apply GRUB changes"
        reboot_timeout: 300
        pre_reboot_delay: 5
        post_reboot_delay: 30
        test_command: uptime