---
- name: Configure NVIDIA Container Toolkit
  hosts: all
  become: true
  tasks:
    - name: Download NVIDIA GPG key
      ansible.builtin.get_url:
        url: https://nvidia.github.io/libnvidia-container/gpgkey
        dest: /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
        mode: '0644'
        owner: root
        group: root

    - name: Configure NVIDIA repository
      ansible.builtin.shell: |
        curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
        sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
        tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

    - name: Update the package list
      ansible.builtin.apt:
        update_cache: true

    - name: Install NVIDIA Container Toolkit
      ansible.builtin.apt:
        name: nvidia-container-toolkit
        state: present

    - name: Configure NVIDIA runtime for Docker
      ansible.builtin.shell: nvidia-ctk runtime configure --runtime=docker

    - name: Restart Docker service
      ansible.builtin.service:
        name: docker
        state: restarted
