---
- name: Configure NVIDIA Container Toolkit
  hosts: all
  become: true
  tasks:
    - name: Add NVIDIA GPG key and configure the repository
      ansible.builtin.shell: |
        curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
        && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
        sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
        tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
      args:
        warn: false

    - name: Update the package list
      ansible.builtin.apt:
        update_cache: true

    - name: Install NVIDIA Container Toolkit
      ansible.builtin.apt:
        name: nvidia-container-toolkit
        state: present

    - name: Configure NVIDIA runtime for Docker
      ansible.builtin.shell: nvidia-ctk runtime configure --runtime=docker

    - name: Restart Docker service
      ansible.builtin.service:
        name: docker
        state: restarted
