---
- name: Copy SSH public key to remote hosts
  hosts: all
  tasks:
    - name: Add the SSH public key to the authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"  # Specify the user, default is the ansible user
        state: present
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC15idrQgh+ZGvE0eRoX75SuCNr2wWBSvPT5Le8la+8gxkIe1gZmEoTap0rRnpNiGyr3tp3YcyJnd2bdQ/xDMoMcUdq/9hd6j4ztz5ndxrEA0QRQ7hkZ4ISWdfiuAeyZRHi/1S9cnuusdcPI/27H1spaBhv5iNK7tqC7uPgX6p6XH70R+N9zIjVwkucaTACT+tiNJVZqcMvFm5VMzrPuasCrZHghcbwC9ljbRWDmx6Ys48C5KsxflbCSjfxlX6dDVTRN3bLregkPGBgxsXYSaEm1aM0nGRDH/3/XieiAhl0aYne2/zpG6elRfE0mntdsKKwSCx2uBkClaUGSbmOK9N3RUHeQzrXBTWGlpquBu4jFwqXpLdFBJvszxfgJqLY/uYJBYy1WJFKiK+5xRWfRg4E756UlF7BPIXIK5ixpvt3PXDglyi8iqgHzEpSAP+BF1hPYZj6cs0LwhHFEqJQevTSKhBXet2t0DolVx9XkaJFVxmjDQZgBmQfthRXq3+0KkU= ubuntu@node065"
