---
- name: Copy SSH public key to remote hosts
  hosts: all
  tasks:
    - name: Add the SSH public key to the authorized_keys
      authorized_key:
        user: "{{ ansible_user }}"  # Specify the user, default is the ansible user
        state: present
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9jD/aQ0qLkSqj4iEwpmVEFmmovm3LhL7s+EP5KxZzLMBFo9ds5Bbwa3/aHEBhyUjo6e3Auoqz9aZWvt9HINuhXopPX7YdrVowc8Zo8oLi+J1UB4EFUpPzGHqtpxpIyy3ZCav32LqqS75X5+40iFhzeF0Thk7MFbmdIq1c/kHKu6ZHE5vyjY9hI+Qdo9fbjFvdtAiOBLAcccbxaxyL1wFkchdgm1mBLd9oG8TKi4wBLYPy0a3ksl6V7Pf7FhiKq6ONzxwq2mSbnjHwxYVLJ67mHRQxyDLCL2/GMFcSTXxas5ebOcDQxxazQuF9W9t7RuUvd3hWBsD43cAnqiw6ByUsaqh1yXOMEYnt19Y1V+9gPPE69dw3t4AqpcaxzIU1Ivw2XSHnoC+uQlSEhyCiYLN5eGamvjp6+7sn5HANXluv/8B04htkgjqZ3yfWeFDpoFPy3rEkO3Z/P6RcgR1OoNDt3J2YIfRl1qr20/ACM43buyfo9lq0sy7FgXdCiVJEsNE= ubuntu@node033"
