---
- name: Extend Logical Volume to maximum size
  hosts: all
  become: yes
  tasks:
    - name: Extend logical volume to use all available space
      lvol:
        vg: ubuntu-vg
        lv: ubuntu-lv
        size: +100%FREE

    - name: Resize filesystem
      filesystem:
        dev: /dev/ubuntu-vg/ubuntu-lv
        fstype: ext4
        resizefs: yes