- name: Bring up IB interfaces
  hosts: all
  become: true
  tasks:
    - name: Bring up interface ibs948
      command: ip link set ibs948 up

    - name: Bring up interface ibs844
      command: ip link set ibs844 up