---
- name: Install CUDA Toolkit
  hosts: all
  become: true
  tasks:
    - name: Run the CUDA installer script
      command: sh ~/nfs/cuda/cuda_12.4.0_550.54.14_linux.run --silent --toolkit --samples --no-dkms
      args:
        chdir: ~/nfs/cuda
      register: cuda_install_output
      environment:
        ACCEPT_EULA: "accept"
    
    - name: Check the CUDA installer output
      debug:
        var: cuda_install_output.stdout
