---
- name: Install Lustre packages and restart exa-client-deploy service
  hosts: all
  become: yes
  tasks:
    - name: Install Lustre packages from /home/ubuntu/nfs/storage/ddn/debs/5.15.0-94-generic/
      ansible.builtin.command:
        cmd: dpkg -i /home/ubuntu/nfs/storage/ddn/debs/5.15.0-94-generic/lustre-*
      args:
        chdir: /home/ubuntu/nfs/storage/ddn/debs/5.15.0-94-generic/
