---
- name: Install Lustre packages and restart exa-client-deploy service
  hosts: all
  become: yes
  tasks:
    - name: Install Lustre client modules package
      ansible.builtin.apt:
        deb: /home/ubuntu/nfs/storage/ddn/debs/5.15.0-94-generic/lustre-client-modules-5.15.0-94-generic_2.14.0-ddn136-1_amd64.deb
      register: modules_install

    - name: Install Lustre client utils package
      ansible.builtin.apt:
        deb: /home/ubuntu/nfs/storage/ddn/debs/5.15.0-94-generic/lustre-client-utils_2.14.0-ddn136-1_amd64.deb
      register: utils_install
      when: modules_install is success

    - name: Install Lustre dev package
      ansible.builtin.apt:
        deb: /home/ubuntu/nfs/storage/ddn/debs/5.15.0-94-generic/lustre-dev_2.14.0-ddn136-1_amd64.deb
      register: dev_install
      when: utils_install is success

    - name: Check installation status
      ansible.builtin.fail:
        msg: "Failed to install one or more Lustre packages"
      when: modules_install is failed or utils_install is failed or dev_install is failed