- name: Bring up IB interfaces
  hosts: all
  become: true
  tasks:
    - name: Bring up interface ibs948
      command: ip link set ibs948 up

    - name: Bring up interface ibs844
      command: ip link set ibs844 up

    - name: Run ibdev2netdev to map IB devices to network devices
      command: ibdev2netdev
      register: ibdev2netdev_output

    - name: Display ibdev2netdev output
      debug:
        var: ibdev2netdev_output.stdout