- name: Configure NFS mount
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      apt:
        name:
          - nfs-common
        state: present
        force: yes

    - name: Ensure the NFS directory exists
      file:
        path: /home/ubuntu/nfs
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Temporary mount NFS share
      command: "mount -t nfs 10.65.0.5:/mnt/jfs/nfs /home/ubuntu/nfs"

    - name: Verify disk usage
      shell: df -h
      register: disk_usage

    - name: Display disk usage
      debug:
        var: disk_usage.stdout