---
- name: Update system, install ipmitool, and set BMC password
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install ipmitool
      ansible.builtin.apt:
        name: ipmitool
        state: present

    - name: Set BMC admin password
      ansible.builtin.command:
        cmd: >
          ipmitool user set password 2 Hjai@bmc20240717